In [1]:
%matplotlib inline
import math
import numpy as np
from matplotlib import pyplot as plt

# Linear Equation

A linear equation is an equation that describes a straight line when plotted on a graph e.g. $x+4y+5z = 5$. There is no terms like $x^2$ or $xy$.

For example the system of linear equations:
$$
\begin{align*}
x_1 + x_2 + x_3 &= 6 \\
2x_1 + 3x_2 + x_3 &= 11 \\
-3x_1 + 4x_2 - 2x_3 &= -1
\end{align*}
$$

In general, a system of linear equations can be written in matrix form as:

$$
A x = B
$$

where $A = \begin{bmatrix}
1 & 1 & 1 \\
2 & 3 & 1 \\
-3 & 4 & -2
\end{bmatrix}$, $x = \begin{bmatrix}
x_1 \\
x_2 \\
x_3
\end{bmatrix}$ , and $B = \begin{bmatrix}
6 \\
11 \\
-1
\end{bmatrix}$. Our goal is to find $x$.



## Solving using Gaussian Elimination:

Gaussian elimination is a method for solving systems of linear equations. It consists of two steps:

1. **Forward elimination:** Transform the matrix $A$ into an upper triangular matrix.
2. **Back substitution:** Solve for the unknowns starting from the last equation.



show how to do step-by-step for forward elimination the example above
To perform forward elimination step-by-step for the example system:

1. **Write the augmented matrix:**

$$
\left[
\begin{array}{ccc|c}
1 & 1 & 1 & 6 \\
2 & 3 & 1 & 11 \\
-3 & 4 & -2 & -1
\end{array}
\right]
$$

2. **Eliminate $x_1$ from rows 2 and 3:**

- Row 2: $R_2 - 2R_1$
- Row 3: $R_3 + 3R_1$

Result:

$$
\left[
\begin{array}{ccc|c}
1 & 1 & 1 & 6 \\
0 & 1 & -1 & -1 \\
0 & 7 & 1 & 17
\end{array}
\right]
$$

3. **Eliminate $x_2$ from row 3:**

- Row 3: $R_3 - 7R_2$

Result:

$$
\left[
\begin{array}{ccc|c}
1 & 1 & 1 & 6 \\
0 & 1 & -1 & -1 \\
0 & 0 & 8 & 24
\end{array}
\right]
$$

Now the matrix is upper triangular and ready for back substitution.


step-by-step back substitution:

1. Start with the upper triangular matrix from forward elimination:

$$
\left[
\begin{array}{ccc|c}
1 & 1 & 1 & 6 \\
0 & 1 & -1 & -1 \\
0 & 0 & 8 & 24
\end{array}
\right]
$$

2. **Solve for $x_3$ using the last row:**

$$
8x_3 = 24 \implies x_3 = 3
$$

3. **Substitute $x_3$ into the second row to solve for $x_2$:**

$$
x_2 - x_3 = -1 \implies x_2 - 3 = -1 \implies x_2 = 2
$$

4. **Substitute $x_2$ and $x_3$ into the first row to solve for $x_1$:**

$$
x_1 + x_2 + x_3 = 6 \implies x_1 + 2 + 3 = 6 \implies x_1 = 1
$$

**Final solution:**

$$
x_1 = 1,\quad x_2 = 2,\quad x_3 = 3
$$

In [2]:
'''
write down your code here
A = ...
B = ...
def forward_elim(A, B):
    ...
    return A, B
def back_sub(A, B):
    ...
    return A, B
'''

A = np.array([[1., 1., 1.],
              [2., 3., 1.],
              [-3., 4., -2.]])

B = np.array([6., 11., -1.])

def forward_elim(A, B):
    a = A.copy()
    b = B.copy()
    n = len(b)
    for pivot in range(n-1):
        for target in range(pivot+1, n):
            if a[target,pivot] == 0: 
                continue
            coef = a[target,pivot]/a[pivot,pivot]
            a[target] = a[target] - coef * a[pivot]
            b[target] = b[target] - coef * b[pivot]
    return a, b

def back_sub(A, B):
    a = A.copy()
    b = B.copy()
    n = len(b)
    
    for i in range(n - 1, -1, -1):

        # This makes the pivot element equal to 1.
        pivot_val = a[i, i]
        a[i] = a[i] / pivot_val
        b[i] = b[i] / pivot_val

        # Eliminate the elements above the pivot:
        for j in range(i - 1, -1, -1):
            factor = a[j, i]
        
            # make the element a[j, i] zero.
            a[j] = a[j] - factor * a[i]
            b[j] = b[j] - factor * b[i]

    return a, b # Return the identity matrix and the solution vector

def gauss_elim(A, B):
    A, B = forward_elim(A, B)
    A, B = back_sub(A, B)
    return A, B

A, B = gauss_elim(A, B)
print(A)
print(B)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[1. 2. 3.]


In [3]:
#test your function with the following code

np.random.seed(100)
A = np.random.rand(100,100)
x = np.random.rand(100)
B = A @ x
_, sol = gauss_elim(A, B)
print("solution error:", x - sol)

solution error: [-1.75748305e-12  5.99520433e-15 -8.46545056e-13 -5.41316991e-13
  2.03392858e-13  1.02784448e-12  1.16490151e-13  1.03184128e-12
 -1.63608016e-12  2.69312350e-13 -9.22595333e-14  2.92738056e-13
 -2.02171613e-13 -1.12132525e-14 -1.54043445e-14 -5.59829960e-13
 -1.84186000e-13  1.30007116e-12  1.14908083e-12 -7.64333041e-13
  2.91877633e-13 -6.79456491e-13  6.42874642e-13 -1.55420121e-12
 -3.64208663e-13 -7.71398570e-13 -2.88657986e-15 -8.36164471e-13
  3.60822483e-14  5.09592368e-14 -1.29374289e-12  7.01327885e-13
  1.08624221e-12  2.08118245e-12 -8.71303030e-13 -1.16162635e-12
 -1.81477056e-12  6.95887792e-13  7.12985226e-13 -3.32345262e-13
  3.11861648e-13 -1.00033870e-12 -8.50985948e-13 -1.11910481e-13
  6.01518835e-13  4.22550883e-13  2.77666778e-13  3.09308135e-13
  1.57185376e-12  1.34536826e-12 -1.83186799e-14 -6.21530605e-13
  1.61437530e-12 -5.79980508e-13 -1.03694830e-13  8.20565838e-13
 -7.60835839e-13 -1.73203119e-12 -1.18426102e-12 -1.40498724e-13
 -9.91429

In practice, you can use a functon `np.linalg.solve`

In [4]:
sol2 = np.linalg.solve(A, B)
print("solution error:", x - sol2)

solution error: [ 1.91069383e-13 -3.10862447e-15  3.96349620e-14  8.08797473e-14
  8.65973959e-15 -6.37268016e-14  2.60069744e-14 -1.28286270e-13
  1.50407464e-13 -4.82669460e-14  9.43689571e-15 -3.17523785e-14
  3.09752224e-14 -3.80806497e-14  9.18709553e-15  7.67164110e-14
  4.25770530e-14 -1.70197190e-13 -1.37445610e-13  1.07747145e-13
 -7.38298311e-14  6.30606678e-14 -7.08322290e-14  1.77635684e-13
  5.17919041e-14  8.14001644e-14  4.45476989e-14  1.14741550e-13
 -2.58681965e-14 -1.12132525e-14  1.48103751e-13 -8.37108161e-14
 -1.46160861e-13 -2.52936561e-13  7.94364574e-14  1.21347377e-13
  1.99618100e-13 -8.17124146e-14 -6.27276009e-14  2.71449530e-14
 -4.75175455e-14  1.32074907e-13  9.00390873e-14 -3.55271368e-14
 -5.55111512e-14 -9.64783808e-14 -3.61932706e-14 -4.41868764e-14
 -1.38666856e-13 -1.38999923e-13  2.00395256e-14  6.38655795e-14
 -1.92734717e-13  6.18394225e-14  2.91988655e-14 -9.01501096e-14
  1.09023901e-13  2.22738494e-13  1.18460797e-13 -1.11022302e-15
  4.99600

The time complexity for solving a system of $n$ linear equations  ($A$ is $n \times n$ matrix) using Gaussian elimination is $O(n^3)$.

The best-known asymptotic running time is $O(n^\omega)$ (same running time as two n×n matrix multiplication).

The exponent $\omega$ determines how fast we can multiply matrices and solve linear systems. Every tiny improvement means huge speedups for scientific computing, machine learning, and physics simulations! Reducing $\omega$ is a major achievement in theoretical computer science.


| Year | Bound on ω | Authors |
|------|------------|-----------------------------------------------|
| 1969 | 2.8074     | Strassen                                   |
| 1978 | 2.796      | Pan                                        |
| 1979 | 2.780      | Bini, Capovani, Romani                     |
| 1981 | 2.522      | Schönhage                                  |
| 1981 | 2.517      | Romani                                     |
| 1981 | 2.496      | Coppersmith, Winograd                      |
| 1986 | 2.479      | Strassen                                   |
| 1990 | 2.3755     | Coppersmith, Winograd                      |
| 2010 | 2.3737     | Stothers                                   |
| 2012 | 2.3729     | Williams                                   |
| 2014 | 2.3728639  | Le Gall                                    |
| 2020 | 2.3728596  | Alman, Williams                            |
| 2022 | 2.371866   | Duan, Wu, Zhou                             |
| 2024 | 2.371552   | Williams, Xu, Xu, and Zhou                 |
| 2024 | 2.371339   | Alman, Duan, Williams, Xu, Xu, and Zhou    |

